version: '4'

services:
  postgres:
    container_name: atlas_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: umut
      POSTGRES_PASSWORD: umut
      PGDATA: /var/lib/postgresql/data
    volumes:
      - atlas_postgres:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: atlas_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - atlas_redis:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: atlas_redis-insight
    restart: always
    ports:
      - "5540:5540"

#  auth-service:
#    container_name: atlas_auth
#    build: ./services/auth
#    ports:
#      - "8090:8090"
#    networks:
#      - atlas_network
#    depends_on:
##      - config-server
##      - discovery-server
#      - postgres

volumes:
  atlas_postgres: {}
  atlas_redis: {}

networks:
  atlas_network: {}