groups:
  - name: microservices-alerts
    rules:
      - alert: HighCpuUsage
        expr: system_cpu_usage > 0.1
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 10% ({{ $value }}) on instance {{ $labels.instance }}"