spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/atlas
    username: umut
    password: umut
    driver-class-name: org.postgresql.Driver
  jpa :
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  messages:
    basename: i18n/messages
    encoding: UTF-8

application:
  security:
    jwt:
      secret: githubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidil
      accessTokenExpiration: 8640000
      refreshTokenExpiration: 8640000

server:
  port: 8090